function [jsonTreeStr] = convertTreeToJson(objTree)
%CONVERTTREETOJSON Convert the tree object generated by the product
%traceability model to a JSON string.
%
%   Input:
%       - objTree
%         An object array representing a traceability tree. Please see
%         convertVehEventsToTraceTree.m for more details.%
%   Output:
%       - jsonTree
%         The output JSON string. An example will be:
%           '{"name":"Top Level","parent":null,"children":[{"name":"Level
%           2: A","parent":"Top Level","children":[{"name":"Son of
%           A","parent":"Level 2: A"},{"name":"Daughter of
%           A","parent":"Level 2: A"}]},{"name":"Level 2: B","parent":"Top
%           Level"}]}'
%
% Yaguang Zhang, Purdue, 09/20/2018

assert(~isempty(objTree), 'The input tree object is empty!');

% Width-first search.
indicesRootNodes = find( ...
    arrayfun(@(node) all(isnan(node.parent)), objTree) ...
    );
% An empty holder for the results.
jsonTreeObj = convertTreeBranchToJsonObj();

for idxRootNode = indicesRootNodes
    jsonTreeObj(end+1) = convertTreeBranchToJsonObj(objTree, idxRootNode);
end

% Convert the object to JSON string.
jsonTreeStr = jsonencode(jsonTreeObj);
end

% EOF