function [ branchJsonObj ] = convertTreeBranchToJsonObj(objTree, ...
    branchTopNodeIdx)
%CONVERTTREEBRANCHTOJSONOBJ Convert a branch identified by its top node
%index to a Matlab object which is ready for the JSON tree object needed in
%convertTreeToJson.m.
%
%   Detailed explanation goes here
%
% Yaguang Zhang, Purdue, 09/20/2018

% Helpers.
fctGenerateEmptyTreeObj = @() struct( ...
    ... % Essential infomation for a tree.
    'name', {}, 'parent', {}, 'children', {}, ...
    ... % Extra infomation available.
    'fileIdx', {}, ...
    'estiGpsTimeStartUnloading', {}, 'estiGpsTimeEndUnloading', {});

branchJsonObj = fctGenerateEmptyTreeObj();

if (exist('objTree', 'var') && exist('branchTopNodeIdx', 'var'))
    if isempty(objTree(branchTopNodeIdx).childrenNodeIndices)
        % Add current node to jsonTreeObj.
        branchJsonObj(end+1) = struct( ...
            'name', objTree(branchTopNodeIdx).nodeId, ...
            'parent', objTree(branchTopNodeIdx).parent, ...
            'children', NaN, ... % We have no 'children' for this object.
            'fileIdx', objTree(branchTopNodeIdx).fileIdx, ...
            'estiGpsTimeStartUnloading', ...
            objTree(branchTopNodeIdx).estiGpsTimeStartUnloading, ...
            'estiGpsTimeEndUnloading', ...
            objTree(branchTopNodeIdx).estiGpsTimeEndUnloading);
    else        
        childrenJsonObj = fctGenerateEmptyTreeObj();
        for childIdx = objTree(branchTopNodeIdx).childrenNodeIndices
            childrenJsonObj(end+1) = convertTreeBranchToJsonObj(objTree, ...
                childIdx);
        end
        
        % Add current node to jsonTreeObj.
        branchJsonObj(end+1) = struct( ...
            'name', objTree(branchTopNodeIdx).nodeId, ...
            'parent', objTree(branchTopNodeIdx).parent, ...
            'children', childrenJsonObj, ...
            'fileIdx', objTree(branchTopNodeIdx).fileIdx, ...
            'estiGpsTimeStartUnloading', ...
            objTree(branchTopNodeIdx).estiGpsTimeStartUnloading, ...
            'estiGpsTimeEndUnloading', ...
            objTree(branchTopNodeIdx).estiGpsTimeEndUnloading);
    end
end

% EOF