function vehicleEvents = convertStatesToVehEvents(files, states)
%CONVERTsTATESTOVEHEVENTS Convert the GPS tracks stored in files and the
%cooresponding harvesting state labels.
%
% Inputs:
%   - files, states
%     GPS tracks and their corresponding harvesting state labels.
% Output:
%   - vehicleEvents
%     A two column cell with the structure {'vehId', vehEvents}, where
%     vehEvents is a struct array generated by:
%         genVehEventsForVeh(vehId, files, states)
%
% Yaguang Zhang, Purdue, 11/10/2017

disp(' ')
disp('    convertStatesToVehEvents: ')
uniqVehIds = unique({files.id}');

numUniqVehIds = length(uniqVehIds);
vehicleEvents = cell(numUniqVehIds, 2);
for idxVeh = 1:numUniqVehIds
    disp(['        ', num2str(idxVeh), '/', num2str(numUniqVehIds)]);
    curVehId = uniqVehIds{idxVeh};
    vehicleEvents{idxVeh, 1} = curVehId;
    vehicleEvents{idxVeh, 2} = genVehEventsForVeh(curVehId, files, states);
end
disp('    Done!')
% EOF