hAnimationFig = figure('Name','Animation','NumberTitle','off','Visible','off');

% Create push buttons
btnUpdateMapLimits = uicontrol('Style', 'pushbutton', ...
    'String', 'Update Map Limits',...
    'FontSize', 14, ...
    'Position', [10 10 130 30],...
    'Callback', 'disp(''Callback'')');

btnSetCurrentTime = uicontrol('Style', 'pushbutton', ...
    'String', 'Set Current Time',...
    'FontSize', 14, ...
    'Position', [10 50 130 30],...
    'Callback', 'disp(''Callback'')');

set(hAnimationFig,'Visible','on');
i = 10;
while i>0
    i=i-1;
    disp(num2str(i))
    pause(1)
end