%CREATESTATESSETTINGBUTTONS
% Create and attach one group of states setting buttons onto the animation
% figure at the position corresponding to the variable "positionHeight".
%
% Yaguang Zhang, Purdue, 02/18/2015

% "U" (unloading) button.
hMapStateSettingButtons(indexMapVehiclePressed,1) = uicontrol('Style', 'togglebutton', ...
    'String', 'U', ...
    'FontSize', 10, ...
    'Position', [39 positionHeight 30 15], ...
    'Tag', num2str(indexMapVehiclePressed), ...
    'Callback', 'setStatesToWriteNow');

% "-" (neither loading nor unloading) button. Use "--" to show
% it more clearly.
hMapStateSettingButtons(indexMapVehiclePressed,2) = uicontrol('Style', 'togglebutton', ...
    'String', '--', ...
    'FontSize', 10, ...
    'Position', [69 positionHeight 30 15], ...
    'Tag', num2str(indexMapVehiclePressed), ...
    'Callback', 'setStatesToWriteNow');

% "L" (loading) button.
hMapStateSettingButtons(indexMapVehiclePressed,3) = uicontrol('Style', 'togglebutton', ...
    'String', 'L', ...
    'FontSize', 10, ...
    'Position', [99 positionHeight 30 15], ...
    'Tag', num2str(indexMapVehiclePressed), ...
    'Callback', 'setStatesToWriteNow');

% Vehicle label.
hMapStateSettingButtons(indexMapVehiclePressed,4) = uicontrol('Style', 'text', ...
    'String', strcat(num2str(indexMapVehiclePressed),':'),...
    'FontSize', 11, ...
    'Position', [10 positionHeight 30 15],...
    'BackgroundColor', get(hAnimationFig, 'Color'));

% EOF