%CREATEANIMATIONFIG
% Create the animation figure with UI.
%
% Update: Add SACLING_FACTOR to make it possible to resize the figure for
% different screens. ZYG 05/17/2016
%
% Yaguang Zhang, Purdue, 01/26/2015

% We will set the figure to be visible once the frame is ready to be shown.
hAnimationFig = figure('Name','Animation','NumberTitle','off',...
    'units','normalized','outerposition',[0 0 1 1], ...
    'Visible','off');

SCALING_FACTOR = 2;
% Parameters to specify the locations of distance labels for vehicle pairs.
VEHICLE_DISTS_TEXT_WIDTH = 80*SCALING_FACTOR;
VEHICLE_DISTS_TEXT_HEIGHT = 15*SCALING_FACTOR;
VEHICLE_DISTS_TEXT_GROUP_TOP = 50*SCALING_FACTOR;
VEHICLE_DISTS_TEXT_GROUP_RIGHT = 50*SCALING_FACTOR;

% Parameters to specify the locations of state setting buttons.
STATE_SETTING_BUTTONS_HEIGHT_TOP = 430*SCALING_FACTOR;
STATE_SETTING_BUTTONS_VERTICAL_EDGE = 16*SCALING_FACTOR;

% Specifies the left edge for hAnimationStatesArea in normalized unit.
LEFT_EDGE_STATES_AREA_NORMALIZED = 0.25;
LEFT_EDGE_STATES_AREA_PIXELS = 180*SCALING_FACTOR;

% For text hints.
WIDTH_LEFTSIDE_HINT_PIXELS = 125*SCALING_FACTOR;
HEIGHT_LEFTSIDE_HINT_PIXELS = 40*SCALING_FACTOR;
BOTTOM_DIST_HINT_PIXELS = 500*SCALING_FACTOR;
HEIGHT_STATE_BUTTON_HINT_PIXELS = 450*SCALING_FACTOR;

% Create push buttons / info labels from bottom to top.

% Basic settings.
btnUpdateMapLimits = uicontrol('Style', 'pushbutton', ...
    'String', 'Update Map Limits',...
    'FontSize', 11, ...
    'Position', [10 10 140 30]*SCALING_FACTOR,...
    'Callback', 'updateMapLimits');

btnSetCurrentTime = uicontrol('Style', 'pushbutton', ...
    'String', 'Set Current Time',...
    'FontSize', 11, ...
    'Position', [10 50 140 30]*SCALING_FACTOR,...
    'Callback', 'resetCurrentTime');

% Text first so that it won't block editSetPlaybackSpeed.
uicontrol('Style', 'text', ...
    'String', 'Playback Speed:', ...
    'FontSize', 11, ...
    'Position', [10 110 90 30]*SCALING_FACTOR,...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', get(hAnimationFig, 'Color'));

editSetPlaybackSpeed = uicontrol('Style', 'edit', ...
    'String', num2str(MILLISEC_PER_FRAME), ...
    'FontSize', 10, ...
    'Position', [10 90 140 30]*SCALING_FACTOR,...
    'Callback', 'setPlaybackSpeed');

% Movie generation.
if GENERATE_MOV
    btnGenerateMov = uicontrol('Style', 'pushbutton', ...
        'String', 'Gen Movie',...
        'FontSize', 11, ...
        'Position', [10 200 140 30]*SCALING_FACTOR,...
        'Callback', 'generateMov');
end

% Play controls.
btnJumpBackFrames = uicontrol('Style', 'pushbutton', ...
    'String', '<',...
    'FontSize', 11, ...
    'Position', [39 150 22 22]*SCALING_FACTOR,...
    'Callback', 'jumpBackFrames');

togbtnPauseAnimation = uicontrol('Style', 'togglebutton', ...
    'String', '||',...
    'FontSize', 10, ...
    'Position', [69 150 22 22]*SCALING_FACTOR,...
    'Callback', 'pauseAnimation');

% Can set here to start with the animation being running or paused.
% flagAnimationPaused = true; set(togbtnPauseAnimation, 'Value',
% get(togbtnPauseAnimation, 'Max'));

flagAnimationPaused = false;
set(togbtnPauseAnimation, 'Value', get(togbtnPauseAnimation, 'Min'));

btnJumpForwardFrames = uicontrol('Style', 'pushbutton', ...
    'String', '>',...
    'FontSize', 11, ...
    'Position', [99 150 22 22]*SCALING_FACTOR,...
    'Callback', 'jumpForwardFrames');

% For vehicle state information collection.

btnGenStatesFig = uicontrol('Style', 'pushbutton', ...
    'String', 'Gen State Figure',...
    'FontSize', 11, ...
    'Position', [10 230 140 30]*SCALING_FACTOR,...
    'Callback', 'genStatesFig');

% For vehicle state information collection.

uicontrol('Style', 'text', ...
    'String', 'States Info Collection:', ...
    'FontSize', 11, ...
    'Position', [10 290 110 30]*SCALING_FACTOR,...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', get(hAnimationFig, 'Color'));

btnSaveVehicleStates = uicontrol('Style', 'pushbutton', ...
    'String', 'Save Vehicle States',...
    'FontSize', 11, ...
    'Position', [10 270 140 30]*SCALING_FACTOR,...
    'Callback', 'saveVehicleStates');

% Hints for the user to trigger the state setting buttons.
hMapStateSettingButtonsTriggeredHint = uicontrol('Style', 'text', ...
    'String', ...
    'Click the state label of a vehicle to trigger the state setting buttons for it.', ...
    'FontSize', 11, ...
    'Position', [10 450 125 40]*SCALING_FACTOR,...
    'BackgroundColor', get(hAnimationFig, 'Color'));

% Note: The text area for linking two vehicles and showing their distance
% is created in the file showVehicleDistancesAndStates.m.

% Set 2 plot areas accroding to HEIGHT_ANIMATION_STATE_TIMELINES_AREA.
heightAnimationStateTimelinesArea = floor(HEIGHT_ANIMATION_STATE_TIMELINES_AREA*10);
% Limit it between 1 and 9.
heightAnimationStateTimelinesArea = min(heightAnimationStateTimelinesArea,9);
heightAnimationStateTimelinesArea = max(heightAnimationStateTimelinesArea,1);

% The figure area inside the animation figure for showing animation on a
% map.
hAnimationMapArea = subplot(10,1,...
    1:(10 - heightAnimationStateTimelinesArea));
% The figure area inside the animation figure for setting states.
hAnimationStatesArea = subplot(10,1,...
    (11 - heightAnimationStateTimelinesArea):10);

% Please keep this line, or the callbacks may not work. Note that we don't
% make the figure visible here in this script. We will use
% "set(hAnimationFig, 'Visible', 'on')" to do so later. Just remeber to use
% "drawnow" when necessary to make sure all the callbacks will be effective
% and the appearances of the uicontrols are up-to-date.

% EOF