% REFRESHCOLLECTORGUI Clear workspace and create GUI of the collector.
%
% Yaguang Zhang, Purdue, 04/01/2015

% Clear workspace to speed up the program.
clearvars -except fileFolder fileFolderSet IS_RELATIVE_PATH ...
    MIN_SAMPLE_NUM_TO_IGNORE ...
    USE_GPS_DATA_VARIABLES_IN_CURRENT_WORKSPACE ...
    ...
    files fileIndicesCombines fileIndicesTrucks ...
    fileIndicesGrainKarts ...
    fileIndicesSortedByStartRecordingGpsTime ...
    fileIndicesSortedByEndRecordingGpsTime ...
    ...
    FULLPATH_FILES_LOADED_HISTORY indexFile locationsRef routeInfo...
    pathInFieldClassificationFile pathInFieldClassificationFilefolder ...
    pathBackupTrainingFilefolder pathBackupLocationsRefFile;

% Create the collector for manual location info collection process.
collectorGUI;

% EOF